export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES';
export const GET_VIDEOGAME_NAME = 'GET_VIDEOGAME_NAME';
export const GET_GAME_BY_ID = 'GET_GAME_BY_ID';

export const GET_GENRES = 'GET_GENRES';
export const GET_PLATFORMS = 'GET_PLATFORMS';

export const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
export const FILTER_DB_API = 'FILTER_DB_API';
export const ORDER_BY_AZ = 'ORDER_BY_AZ';
export const ORDER_BY_RATING = 'ORDER_BY_RATING';

export const CREATE_GAME = 'CREATE_GAME';